# Generated by Django 4.2.26 on 2025-11-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Cliente')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['client_id'],
            },
        ),
    ]
